### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by KDAkasa** [ziplab/LITv2#15]
Hello, thank you for your contribution to science. However, I encountered the following issue while running your object detection code：
Traceback (most recent call last):
  File "/tmp/pycharm_project_764/tools/train.py", line 194, in <module>
    main()
  File "/tmp/pycharm_project_764/tools/train.py", line 183, in main
    train_detector(
  File "/tmp/pycharm_project_764/mmdet/apis/train.py", line 186, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/tmp/pycharm_project_764/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 146, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/tmp/pycharm_project_764/mmdet/models/detectors/base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/tmp/pycharm_project_764/mmdet/models/detectors/two_stage.py", line 142, in forward_train
    x = self.extract_feat(img)
  File "/tmp/pycharm_project_764/mmdet/models/detectors/two_stage.py", line 82, in extract_feat
    x = self.backbone(img)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/pycharm_project_764/mmdet/models/backbones/litv2.py", line 631, in forward
    x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/pycharm_project_764/mmdet/models/backbones/litv2.py", line 481, in forward
    x_down, Wh, Ww = self.downsample(x, H, W)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/pycharm_project_764/mmdet/models/backbones/litv2.py", line 387, in forward
    _, _, new_H, new_W = x.shape
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by HubHop** [comment]
Hi @KDAkasa, thanks for using our code. I've just updated LITv2 detection scripts with the latest version of MMDetection (v0.3.2). The updated script can obtain same evaluation results.

```bash
11/17 17:31:51 - mmengine - INFO - Epoch(test) [4850/5000]    eta: 0:00:07  time: 0.0504  data_time: 0.0016  memory: 726  
11/17 17:31:53 - mmengine - INFO - Epoch(test) [4900/5000]    eta: 0:00:05  time: 0.0510  data_time: 0.0017  memory: 709  
11/17 17:31:56 - mmengine - INFO - Epoch(test) [4950/5000]    eta: 0:00:02  time: 0.0504  data_time: 0.0016  memory: 726  
11/17 17:31:58 - mmengine - INFO - Epoch(test) [5000/5000]    eta: 0:00:00  time: 0.0503  data_time: 0.0016  memory: 726  
11/17 17:32:03 - mmengine - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=0.96s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=26.22s).
Accumulating evaluation results...
DONE (t=8.44s).
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.440
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.652
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.471
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.272
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.481
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.581
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.595
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.595
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.595
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.419
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.639
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.749
11/17 17:32:40 - mmengine - INFO - bbox_mAP_copypaste: 0.440 0.652 0.471 0.272 0.481 0.581
11/17 17:32:41 - mmengine - INFO - Epoch(test) [5000/5000]    coco/bbox_mAP: 0.4400  coco/bbox_mAP_50: 0.6520  coco/bbox_mAP_75: 0.4710  coco/bbox_mAP_s: 0.2720  coco/bbox_mAP_m: 0.4810  coco/bbox_mAP_l: 0.5810  data_time: 0.0016  time: 0.0505
```

Please feel free to have a try and let me know if you have further questions.

**Comment by KDAkasa** [comment]
I found the following solution and made changes to the code, I hope you can adopt it：
class DTM(nn.Module):
    r""" Deformable Token Merging.

    Link: https://arxiv.org/abs/2105.14217

    Args:
        input_resolution (tuple[int]): Resolution of input feature.
        dim (int): Number of input channels.
        norm_layer (nn.Module, optional): Normalization layer.  Default: nn.LayerNorm
    """

    def __init__(self, input_resolution, dim, norm_layer=nn.LayerNorm):
        super().__init__()
        self.input_resolution = input_resolution
        self.dim = dim
        self.kernel_size = 2
        self.stride = 2
        self.padding = 0
        self.c_in = dim
        self.c_out = dim*2
        self.dconv = DeformConv2dPack(dim, dim*2, kernel_size=2, stride=2, padding=0)
        self.norm_layer = nn.BatchNorm2d(dim*2)
        self.act_layer = nn.GELU()

    def forward(self, x, H, W):
        """
        x: B, H*W, C
        """
        B, L, C = x.shape
        x = x.reshape(B, H, W, C).permute(0, 3, 1, 2).contiguous()
        x = self.dconv(x)
        # _, _, new_H, new_W = x.shape
        # x = self.act_layer(self.norm_layer(x)).flatten(2).transpose(1, 2)
        x_tensor = x[0]  # 获取张量部分
        _, _, new_H, new_W = x_tensor.shape
        x = self.act_layer(self.norm_layer(x_tensor)).flatten(2).transpose(1, 2)
        return x, new_H, new_W

**Comment by HubHop** [comment]
I see...DTM in LITv1 will return the learned offsets for visualization purpose. But in this repo I removed it. Thanks for letting me know that!
